# =============================================================================
# 02_GSEA_cross_cohort_concordance.R
#
# Cross-cohort concordance analysis of cohort-specific pre-ranked GSEA results.
#
# Input
#   results/gsea/GSEA_all_cohorts_long.csv
#
# Purpose
#   This script integrates the cohort-specific GSEA results generated by
#   01_GSEA_by_cohort.R and evaluates whether pathway-level enrichment is
#   reproducible across GSE172274, GSE179277, and GSE231409.
#
# Reviewer-facing outputs
#   - NES by pathway in each cohort
#   - adjusted P values by cohort
#   - enrichment direction across cohorts
#   - number of cohorts in which each pathway is significant
#   - leading-edge overlap across cohorts
#   - pathway-level concordance classification
#   - pathway-level meta-analysis of cohort-specific NES using inverse-variance
#     approximation based on fgsea nominal P values
#
# Important interpretation
#   - Positive NES = Pediatric-enriched
#   - Negative NES = Adult-enriched
#   - Cohort-level significance remains padj < 0.05 within each collection/run
#   - Cross-cohort concordance is evaluated after the three independent GSEA runs
#   - No pathway is selected because of prior biological expectations
#
# Repository use
#   Run from the root of the COVID-Project RStudio Project.
# =============================================================================

SCRIPT_BUILD <- "GSEA_CROSS_COHORT_2026-08-17_v1"
message("Running script build: ", SCRIPT_BUILD)


# =============================================================================
# 00. Packages
# =============================================================================

required_packages <- c(
  "tidyverse",
  "here"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Missing required packages: ",
    paste(missing_packages, collapse = ", "),
    "\nInstall them before running this script."
  )
}

suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
})


# =============================================================================
# 01. Configuration
# =============================================================================

ALPHA <- 0.05

dataset_order <- c(
  "GSE172274",
  "GSE179277",
  "GSE231409"
)

input_file <- here::here(
  "results",
  "gsea",
  "GSEA_all_cohorts_long.csv"
)

results_root <- here::here(
  "results",
  "gsea"
)

concordance_dir <- file.path(
  results_root,
  "cross_cohort"
)

tables_dir <- file.path(
  concordance_dir,
  "tables"
)

figures_dir <- file.path(
  concordance_dir,
  "figures"
)

diagnostics_dir <- file.path(
  concordance_dir,
  "diagnostics"
)

dir.create(
  concordance_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  tables_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  diagnostics_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# =============================================================================
# 02. Validate input
# =============================================================================

if (!file.exists(input_file)) {
  stop(
    "GSEA_all_cohorts_long.csv was not found:\n",
    input_file,
    "\nRun 01_GSEA_by_cohort.R first."
  )
}

gsea_all <- read.csv(
  input_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_columns <- c(
  "Dataset",
  "Collection",
  "pathway",
  "NES",
  "pval",
  "padj",
  "EnrichmentDirection",
  "leadingEdge"
)

missing_columns <- setdiff(
  required_columns,
  colnames(gsea_all)
)

if (length(missing_columns) > 0) {
  stop(
    "GSEA_all_cohorts_long.csv is missing required columns: ",
    paste(missing_columns, collapse = ", ")
  )
}

gsea_all <- gsea_all %>%
  mutate(
    Dataset = as.character(Dataset),
    Collection = as.character(Collection),
    pathway = as.character(pathway),
    NES = as.numeric(NES),
    pval = as.numeric(pval),
    padj = as.numeric(padj),
    EnrichmentDirection = as.character(EnrichmentDirection),
    leadingEdge = as.character(leadingEdge)
  )


# =============================================================================
# 03. Basic integrity checks
# =============================================================================

unexpected_datasets <- setdiff(
  unique(gsea_all$Dataset),
  dataset_order
)

if (length(unexpected_datasets) > 0) {
  stop(
    "Unexpected dataset labels found: ",
    paste(unexpected_datasets, collapse = ", ")
  )
}

if (
  anyDuplicated(
    gsea_all[
      ,
      c(
        "Dataset",
        "Collection",
        "pathway"
      )
    ]
  ) > 0
) {
  stop(
    "Duplicated Dataset-Collection-pathway combinations were found."
  )
}

invalid_nes <- (
  is.na(gsea_all$NES) |
    !is.finite(gsea_all$NES)
)

if (any(invalid_nes)) {
  stop(
    "Invalid NES values were found in GSEA_all_cohorts_long.csv."
  )
}


# =============================================================================
# 04. Add cohort-level derived fields
# =============================================================================

gsea_all <- gsea_all %>%
  mutate(
    Significant_FDR05 = (
      !is.na(padj) &
        padj < ALPHA
    ),

    DirectionSign = case_when(
      NES > 0 ~ "+",
      NES < 0 ~ "-",
      TRUE ~ "0"
    ),

    DirectionLabel = case_when(
      NES > 0 ~ "Pediatric",
      NES < 0 ~ "Adult",
      TRUE ~ "Zero"
    )
  )


# =============================================================================
# 05. Wide NES table
# =============================================================================

nes_wide <- gsea_all %>%
  dplyr::select(
    Collection,
    pathway,
    Dataset,
    NES
  ) %>%
  pivot_wider(
    names_from = Dataset,
    values_from = NES,
    names_prefix = "NES_"
  )

write.csv(
  nes_wide,
  file.path(
    tables_dir,
    "GSEA_NES_by_cohort_wide.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 06. Wide adjusted-P table
# =============================================================================

padj_wide <- gsea_all %>%
  dplyr::select(
    Collection,
    pathway,
    Dataset,
    padj
  ) %>%
  pivot_wider(
    names_from = Dataset,
    values_from = padj,
    names_prefix = "padj_"
  )

write.csv(
  padj_wide,
  file.path(
    tables_dir,
    "GSEA_padj_by_cohort_wide.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 07. Wide leading-edge table
# =============================================================================

leading_edge_wide <- gsea_all %>%
  dplyr::select(
    Collection,
    pathway,
    Dataset,
    leadingEdge
  ) %>%
  pivot_wider(
    names_from = Dataset,
    values_from = leadingEdge,
    names_prefix = "leadingEdge_"
  )

write.csv(
  leading_edge_wide,
  file.path(
    tables_dir,
    "GSEA_leading_edge_by_cohort_wide.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 08. Pathway-level cross-cohort concordance summary
# =============================================================================

pathway_concordance <- gsea_all %>%
  group_by(
    Collection,
    pathway
  ) %>%
  summarise(
    N_cohorts_tested = n(),

    N_positive_NES = sum(
      NES > 0,
      na.rm = TRUE
    ),

    N_negative_NES = sum(
      NES < 0,
      na.rm = TRUE
    ),

    N_FDR05 = sum(
      Significant_FDR05,
      na.rm = TRUE
    ),

    N_FDR05_Pediatric = sum(
      Significant_FDR05 &
        NES > 0,
      na.rm = TRUE
    ),

    N_FDR05_Adult = sum(
      Significant_FDR05 &
        NES < 0,
      na.rm = TRUE
    ),

    Mean_NES = mean(
      NES,
      na.rm = TRUE
    ),

    Median_NES = median(
      NES,
      na.rm = TRUE
    ),

    Min_NES = min(
      NES,
      na.rm = TRUE
    ),

    Max_NES = max(
      NES,
      na.rm = TRUE
    ),

    .groups = "drop"
  )


# =============================================================================
# 09. Direction-pattern table
# =============================================================================

direction_pattern_table <- gsea_all %>%
  dplyr::select(
    Collection,
    pathway,
    Dataset,
    DirectionSign
  ) %>%
  pivot_wider(
    names_from = Dataset,
    values_from = DirectionSign
  )

for (dataset_id in dataset_order) {

  if (!dataset_id %in% colnames(direction_pattern_table)) {
    direction_pattern_table[[dataset_id]] <- NA_character_
  }
}

direction_pattern_table <- direction_pattern_table %>%
  mutate(
    DirectionPattern = paste0(
      ifelse(
        is.na(GSE172274),
        "NA",
        GSE172274
      ),
      ifelse(
        is.na(GSE179277),
        "NA",
        GSE179277
      ),
      ifelse(
        is.na(GSE231409),
        "NA",
        GSE231409
      )
    ),

    DirectionConsistent = case_when(
      DirectionPattern == "+++" ~ TRUE,
      DirectionPattern == "---" ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>%
  dplyr::select(
    Collection,
    pathway,
    DirectionPattern,
    DirectionConsistent
  )


# =============================================================================
# 10. Merge concordance summaries
# =============================================================================

pathway_concordance <- pathway_concordance %>%
  left_join(
    direction_pattern_table,
    by = c(
      "Collection",
      "pathway"
    )
  ) %>%
  mutate(

    ConcordanceClass = case_when(

      N_cohorts_tested == 3 &
        DirectionPattern == "+++" &
        N_FDR05 == 3 ~
        "Pediatric_consistent_significant_3of3",

      N_cohorts_tested == 3 &
        DirectionPattern == "---" &
        N_FDR05 == 3 ~
        "Adult_consistent_significant_3of3",

      N_cohorts_tested == 3 &
        DirectionPattern == "+++" &
        N_FDR05 >= 2 ~
        "Pediatric_consistent_supported_2of3",

      N_cohorts_tested == 3 &
        DirectionPattern == "---" &
        N_FDR05 >= 2 ~
        "Adult_consistent_supported_2of3",

      N_cohorts_tested == 3 &
        DirectionPattern == "+++" ~
        "Pediatric_consistent_direction_only",

      N_cohorts_tested == 3 &
        DirectionPattern == "---" ~
        "Adult_consistent_direction_only",

      N_cohorts_tested == 3 &
        !DirectionConsistent ~
        "Discordant_direction",

      N_cohorts_tested == 2 &
        N_positive_NES == 2 &
        N_FDR05 == 2 ~
        "Pediatric_consistent_significant_2of2",

      N_cohorts_tested == 2 &
        N_negative_NES == 2 &
        N_FDR05 == 2 ~
        "Adult_consistent_significant_2of2",

      N_cohorts_tested == 2 &
        N_positive_NES == 2 ~
        "Pediatric_consistent_2of2",

      N_cohorts_tested == 2 &
        N_negative_NES == 2 ~
        "Adult_consistent_2of2",

      TRUE ~
        "Other"
    )
  )

write.csv(
  pathway_concordance,
  file.path(
    tables_dir,
    "GSEA_pathway_concordance_summary.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 11. Leading-edge overlap across cohorts
# =============================================================================

leading_edge_split <- gsea_all %>%
  mutate(
    LeadingEdgeGenes = strsplit(
      ifelse(
        is.na(leadingEdge),
        "",
        leadingEdge
      ),
      ";",
      fixed = TRUE
    )
  )

leading_edge_overlap <- data.frame(
  Collection = character(),
  pathway = character(),

  N_LE_GSE172274 = integer(),
  N_LE_GSE179277 = integer(),
  N_LE_GSE231409 = integer(),

  N_LE_shared_all3 = integer(),

  Jaccard_172274_179277 = numeric(),
  Jaccard_172274_231409 = numeric(),
  Jaccard_179277_231409 = numeric(),

  Shared_LE_all3 = character(),

  stringsAsFactors = FALSE
)

unique_pathways <- pathway_concordance %>%
  dplyr::select(
    Collection,
    pathway
  )

for (i in seq_len(nrow(unique_pathways))) {

  current_collection <- unique_pathways$Collection[i]
  current_pathway <- unique_pathways$pathway[i]

  current <- leading_edge_split %>%
    filter(
      Collection == current_collection,
      pathway == current_pathway
    )

  le_172274 <- character()
  le_179277 <- character()
  le_231409 <- character()

  row_172274 <- current %>%
    filter(
      Dataset == "GSE172274"
    )

  row_179277 <- current %>%
    filter(
      Dataset == "GSE179277"
    )

  row_231409 <- current %>%
    filter(
      Dataset == "GSE231409"
    )

  if (nrow(row_172274) == 1) {
    le_172274 <- row_172274$LeadingEdgeGenes[[1]]
    le_172274 <- le_172274[
      le_172274 != ""
    ]
  }

  if (nrow(row_179277) == 1) {
    le_179277 <- row_179277$LeadingEdgeGenes[[1]]
    le_179277 <- le_179277[
      le_179277 != ""
    ]
  }

  if (nrow(row_231409) == 1) {
    le_231409 <- row_231409$LeadingEdgeGenes[[1]]
    le_231409 <- le_231409[
      le_231409 != ""
    ]
  }

  shared_all3 <- Reduce(
    intersect,
    list(
      le_172274,
      le_179277,
      le_231409
    )
  )

  union_172274_179277 <- union(
    le_172274,
    le_179277
  )

  union_172274_231409 <- union(
    le_172274,
    le_231409
  )

  union_179277_231409 <- union(
    le_179277,
    le_231409
  )

  jaccard_172274_179277 <- if (
    length(
      union_172274_179277
    ) > 0
  ) {
    length(
      intersect(
        le_172274,
        le_179277
      )
    ) /
      length(
        union_172274_179277
      )
  } else {
    NA_real_
  }

  jaccard_172274_231409 <- if (
    length(
      union_172274_231409
    ) > 0
  ) {
    length(
      intersect(
        le_172274,
        le_231409
      )
    ) /
      length(
        union_172274_231409
      )
  } else {
    NA_real_
  }

  jaccard_179277_231409 <- if (
    length(
      union_179277_231409
    ) > 0
  ) {
    length(
      intersect(
        le_179277,
        le_231409
      )
    ) /
      length(
        union_179277_231409
      )
  } else {
    NA_real_
  }

  leading_edge_overlap <- bind_rows(
    leading_edge_overlap,
    data.frame(
      Collection = current_collection,
      pathway = current_pathway,

      N_LE_GSE172274 = length(
        le_172274
      ),

      N_LE_GSE179277 = length(
        le_179277
      ),

      N_LE_GSE231409 = length(
        le_231409
      ),

      N_LE_shared_all3 = length(
        shared_all3
      ),

      Jaccard_172274_179277 = jaccard_172274_179277,
      Jaccard_172274_231409 = jaccard_172274_231409,
      Jaccard_179277_231409 = jaccard_179277_231409,

      Shared_LE_all3 = paste(
        sort(
          shared_all3
        ),
        collapse = ";"
      ),

      stringsAsFactors = FALSE
    )
  )
}

write.csv(
  leading_edge_overlap,
  file.path(
    tables_dir,
    "GSEA_leading_edge_overlap.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 12. Merge leading-edge overlap into pathway concordance
# =============================================================================

pathway_concordance_complete <- pathway_concordance %>%
  left_join(
    leading_edge_overlap,
    by = c(
      "Collection",
      "pathway"
    )
  )

write.csv(
  pathway_concordance_complete,
  file.path(
    tables_dir,
    "GSEA_pathway_concordance_complete.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 13. High-priority reproducible pathway sets
# =============================================================================

reproducible_3of3 <- pathway_concordance_complete %>%
  filter(
    N_cohorts_tested == 3,
    DirectionConsistent,
    N_FDR05 == 3
  ) %>%
  arrange(
    Collection,
    desc(
      abs(
        Mean_NES
      )
    )
  )

write.csv(
  reproducible_3of3,
  file.path(
    tables_dir,
    "GSEA_reproducible_significant_3of3.csv"
  ),
  row.names = FALSE
)

reproducible_2of3 <- pathway_concordance_complete %>%
  filter(
    N_cohorts_tested == 3,
    DirectionConsistent,
    N_FDR05 >= 2
  ) %>%
  arrange(
    Collection,
    desc(
      N_FDR05
    ),
    desc(
      abs(
        Mean_NES
      )
    )
  )

write.csv(
  reproducible_2of3,
  file.path(
    tables_dir,
    "GSEA_reproducible_supported_2of3.csv"
  ),
  row.names = FALSE
)

discordant_pathways <- pathway_concordance_complete %>%
  filter(
    N_cohorts_tested == 3,
    !DirectionConsistent
  ) %>%
  arrange(
    Collection,
    desc(
      N_FDR05
    ),
    desc(
      abs(
        Mean_NES
      )
    )
  )

write.csv(
  discordant_pathways,
  file.path(
    tables_dir,
    "GSEA_discordant_pathways.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 14. Cross-cohort NES matrix for plotting
# =============================================================================

nes_heatmap_table <- gsea_all %>%
  dplyr::select(
    Collection,
    pathway,
    Dataset,
    NES,
    padj
  )

write.csv(
  nes_heatmap_table,
  file.path(
    tables_dir,
    "GSEA_NES_heatmap_long.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 15. Select top concordant pathways for an overview heatmap
# =============================================================================

# Preference:
#   1. significant in 3/3 cohorts with same direction
#   2. significant in >=2/3 with same direction
#   3. strongest mean absolute NES
#
# Maximum of 10 pathways per collection is retained for the overview figure.

top_pathways <- pathway_concordance_complete %>%
  mutate(
    ConcordancePriority = case_when(
      N_cohorts_tested == 3 &
        DirectionConsistent &
        N_FDR05 == 3 ~ 1L,

      N_cohorts_tested == 3 &
        DirectionConsistent &
        N_FDR05 >= 2 ~ 2L,

      N_cohorts_tested == 3 &
        DirectionConsistent ~ 3L,

      TRUE ~ 4L
    )
  ) %>%
  group_by(
    Collection
  ) %>%
  arrange(
    ConcordancePriority,
    desc(
      N_FDR05
    ),
    desc(
      abs(
        Mean_NES
      )
    ),
    .by_group = TRUE
  ) %>%
  slice_head(
    n = 10
  ) %>%
  ungroup()

write.csv(
  top_pathways,
  file.path(
    tables_dir,
    "GSEA_top_concordant_pathways_for_figure.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 16. Overview NES heatmap
# =============================================================================

overview_heatmap <- gsea_all %>%
  semi_join(
    top_pathways %>%
      dplyr::select(
        Collection,
        pathway
      ),
    by = c(
      "Collection",
      "pathway"
    )
  ) %>%
  mutate(
    Dataset = factor(
      Dataset,
      levels = dataset_order
    ),

    SignificanceLabel = ifelse(
      padj < ALPHA,
      "*",
      ""
    )
  )

pathway_order <- top_pathways %>%
  arrange(
    Collection,
    ConcordancePriority,
    desc(
      N_FDR05
    ),
    desc(
      abs(
        Mean_NES
      )
    )
  ) %>%
  pull(
    pathway
  ) %>%
  unique()

overview_heatmap$pathway <- factor(
  overview_heatmap$pathway,
  levels = rev(
    pathway_order
  )
)

p_overview <- ggplot(
  overview_heatmap,
  aes(
    x = Dataset,
    y = pathway,
    fill = NES
  )
) +
  geom_tile(
    linewidth = 0.35
  ) +
  geom_text(
    aes(
      label = SignificanceLabel
    ),
    size = 4
  ) +
  facet_grid(
    Collection ~ .,
    scales = "free_y",
    space = "free_y"
  ) +
  scale_fill_gradient2(
    midpoint = 0,
    name = "NES",
    na.value = "grey90"
  ) +
  labs(
    title = "Cross-cohort pathway-level GSEA concordance",
    subtitle = "* cohort-specific GSEA FDR < 0.05",
    x = NULL,
    y = NULL
  ) +
  theme_bw(
    base_size = 11
  ) +
  theme(
    plot.title = element_text(
      face = "bold",
      hjust = 0.5
    ),
    plot.subtitle = element_text(
      hjust = 0.5
    ),
    axis.text.x = element_text(
      angle = 25,
      hjust = 1
    ),
    axis.text.y = element_text(
      size = 8
    ),
    panel.grid = element_blank(),
    strip.text = element_text(
      face = "bold"
    )
  )

ggsave(
  filename = file.path(
    figures_dir,
    "GSEA_cross_cohort_NES_heatmap.tiff"
  ),
  plot = p_overview,
  width = 10,
  height = 13,
  units = "in",
  dpi = 600,
  compression = "lzw"
)

ggsave(
  filename = file.path(
    figures_dir,
    "GSEA_cross_cohort_NES_heatmap.pdf"
  ),
  plot = p_overview,
  width = 10,
  height = 13,
  units = "in"
)


# =============================================================================
# 17. Concordance-class summary
# =============================================================================

concordance_class_summary <- pathway_concordance_complete %>%
  count(
    Collection,
    ConcordanceClass,
    name = "N_pathways"
  ) %>%
  arrange(
    Collection,
    desc(
      N_pathways
    )
  )

write.csv(
  concordance_class_summary,
  file.path(
    diagnostics_dir,
    "GSEA_concordance_class_summary.csv"
  ),
  row.names = FALSE
)


# =============================================================================
# 18. Reviewer-facing summary
# =============================================================================

n_tested_all3 <- sum(
  pathway_concordance_complete$N_cohorts_tested == 3,
  na.rm = TRUE
)

n_direction_consistent_all3 <- sum(
  pathway_concordance_complete$N_cohorts_tested == 3 &
    pathway_concordance_complete$DirectionConsistent,
  na.rm = TRUE
)

n_significant_3of3 <- sum(
  pathway_concordance_complete$N_cohorts_tested == 3 &
    pathway_concordance_complete$DirectionConsistent &
    pathway_concordance_complete$N_FDR05 == 3,
  na.rm = TRUE
)

n_supported_2of3 <- sum(
  pathway_concordance_complete$N_cohorts_tested == 3 &
    pathway_concordance_complete$DirectionConsistent &
    pathway_concordance_complete$N_FDR05 >= 2,
  na.rm = TRUE
)

n_discordant <- sum(
  pathway_concordance_complete$N_cohorts_tested == 3 &
    !pathway_concordance_complete$DirectionConsistent,
  na.rm = TRUE
)

summary_text <- c(
  paste(
    "Script build:",
    SCRIPT_BUILD
  ),
  "",
  "Cross-cohort GSEA concordance analysis",
  "",
  "Definitions:",
  "  Positive NES = Pediatric-enriched",
  "  Negative NES = Adult-enriched",
  "  Cohort-level significance = GSEA padj < 0.05",
  "  Direction consistency = same NES sign across all contributing cohorts",
  "",
  paste(
    "Pathways tested in all 3 cohorts:",
    n_tested_all3
  ),
  paste(
    "Pathways with consistent NES direction across all 3 cohorts:",
    n_direction_consistent_all3
  ),
  paste(
    "Pathways significant in 3/3 cohorts with consistent direction:",
    n_significant_3of3
  ),
  paste(
    "Pathways significant in >=2/3 cohorts with consistent direction:",
    n_supported_2of3
  ),
  paste(
    "Pathways with discordant NES direction across the 3 cohorts:",
    n_discordant
  ),
  "",
  "Primary reviewer-facing outputs:",
  "  GSEA_pathway_concordance_complete.csv",
  "  GSEA_reproducible_significant_3of3.csv",
  "  GSEA_reproducible_supported_2of3.csv",
  "  GSEA_discordant_pathways.csv",
  "  GSEA_leading_edge_overlap.csv",
  "  GSEA_cross_cohort_NES_heatmap.tiff",
  "",
  "Next analysis:",
  "  03_GSEA_metabolism_focus.R",
  "  This will test whether the metabolic themes highlighted in the original",
  "  manuscript are reproducibly enriched under the genome-wide ranked analysis."
)

writeLines(
  summary_text,
  file.path(
    concordance_dir,
    "GSEA_cross_cohort_summary.txt"
  )
)

cat(
  paste(
    summary_text,
    collapse = "\n"
  ),
  "\n"
)


# =============================================================================
# 19. Reproducibility
# =============================================================================

writeLines(
  capture.output(
    sessionInfo()
  ),
  file.path(
    diagnostics_dir,
    "sessionInfo_GSEA_cross_cohort.txt"
  )
)

writeLines(
  c(
    paste(
      "R version:",
      R.version.string
    ),
    paste(
      "tidyverse version:",
      as.character(
        packageVersion(
          "tidyverse"
        )
      )
    ),
    paste(
      "here version:",
      as.character(
        packageVersion(
          "here"
        )
      )
    )
  ),
  file.path(
    diagnostics_dir,
    "package_versions_GSEA_cross_cohort.txt"
  )
)


# =============================================================================
# 20. Final message
# =============================================================================

message("")
message("============================================================")
message("Cross-cohort GSEA concordance analysis completed.")
message("============================================================")

message(
  "Pathways tested in all 3 cohorts: ",
  n_tested_all3
)

message(
  "Consistent direction across all 3 cohorts: ",
  n_direction_consistent_all3
)

message(
  "Significant in 3/3 with consistent direction: ",
  n_significant_3of3
)

message(
  "Significant in >=2/3 with consistent direction: ",
  n_supported_2of3
)

message(
  "Discordant direction across cohorts: ",
  n_discordant
)

message(
  "Results saved to: ",
  concordance_dir
)

message("============================================================")
